const assert = require('node:assert/strict')
const logos = require('@techbykyle/svg-logo')
const ACP = require('@techbykyle/svg-logo/icons/ACP')
const Grok = require('@techbykyle/svg-logo/icons/Grok')
const LinkedIn = require('@techbykyle/svg-logo/icons/LinkedIn')
const Npm = require('@techbykyle/svg-logo/icons/Npm')
const metadata = require('@techbykyle/svg-logo/metadata')

assert.equal(logos.default, logos.LoadLogo)
assert.equal(Grok.default, Grok)
assert.equal(ACP.default, ACP)
assert.equal(LinkedIn.default, LinkedIn)
assert.equal(Npm.default, Npm)
assert.equal(ACP.metadata.exportName, 'ACP')
assert.equal(Grok.metadata.exportName, 'Grok')
assert.equal(LinkedIn.metadata.exportName, 'LinkedIn')
assert.equal(Npm.metadata.exportName, 'Npm')
assert.equal(logos.Grok, Grok)
assert.equal(logos.LinkedIn, LinkedIn)
assert.equal(logos.Npm, Npm)
assert.equal(metadata.getIconMetadata('grok'), Grok.metadata)
